services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
  backend:
    build: .
    depends_on:
      - postgres
    environment:
      - DB_URL=${DB_URL}
    ports:
      - 4000:3000

volumes:
  pgdata: