openapi: 3.0.0
info:
  title: Doctor Buddy
  version: 1.0.0
  description: Simple API with Swagger YAML

servers:
  - url: http://localhost:3000

paths:
  /:
    get:
      summary: Returns Hello World
      responses:
        '200':
          description: Successful greeting response
          content:
            text/plain:
              schema:
                type: string
                example: Hello World
  
  /api/doctor/sign-up:
    post:
      summary: Creates doctor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDoctorRequest'
      responses:
        '201':
          description: Successfully signed up
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
  
  /api/doctor/login:
    post:
      summary: Authenticates doctor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDoctorRequest'
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: 
                    type: string

  /api/doctor/{id}:
    get:
      summary: Retrieves doctor's information
      responses:
        '200':
          description: Successfully gets doctor's information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoctorInfoResponse'

    put:
      summary: Updates doctor's information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDoctorInfoRequest'
      responses:
        '200':
          description: Successfully updates doctor's information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string

    delete:
      summary: Soft deletes doctor
      responses:
        '200':
          description: Successfully deleted doctor
          content:
            application/json:
              schema:  
                type: object
                properties:
                  message: 
                    type: string

  /api/patient/:
    post:
      summary: Creates a patient 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePatientRequest'
      responses:
        '200':
          description: Successfully created a patient
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: string
    
    get:
      summary: Retrieve a list of patients
      parameters:
        - name: page
          in: query
          description: Page number
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          description: Maximum number of items to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of patients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPatientResponse'

  /api/patient/{id}:
    get:
      summary: Retrieves patient's information
      responses:
        '200':
          description: Successfully gets patient's information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientInfoResponse'

    put:
      summary: Updates patient's information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePatientRequest'
      responses:
        '200':
          description: Successfully updates patient's information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string

    delete:
      summary: Soft deletes doctor
      responses:
        '200':
          description: Successfully deleted doctor
          content:
            application/json:
              schema:  
                type: object
                properties:
                  message: 
                    type: string


components:
  schemas:
    CreateDoctorRequest:
      type: object
      properties:
        firstName: 
          type: string
        lastName: 
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - firstName
        - lastName
        - email
        - password
    
    LoginDoctorRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    DoctorInfoResponse: 
      type: object
      properties:
        firstName: 
          type: string
        lastName: 
          type: string
        email:
          type: string
    
    UpdateDoctorInfoRequest:
      type: object
      properties:
        firstName: 
          type: string
        lastName: 
          type: string
        email:
          type: string
      required:
        - firstName
        - lastName
        - email
    
    CreatePatientRequest:   
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        contactNumber:
          type: string
        email:
          type: string
      required:
        - firstName
        - lastName
        - contactNumber
    
    PatientInfoResponse: 
      type: object
      properties:
        firstName: 
          type: string
        lastName: 
          type: string
        email:
          type: string
        contactNumber:
          type: string

    UpdatePatientRequest:   
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        contactNumber:
          type: string
        doctorId:
          type: string
        email:
          type: string
      required:
        - firstName
        - lastName
        - contactNumber 
        - doctorId

    PatientInfo: 
      type: object
      required:
        - id
        - firstName
        - lastName
        - contactNumber
        - isDeleted
        - doctorId
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        contactNumber:
          type: string
        isDeleted:
          type: boolean
        doctorId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        email:
          type: string
          format: email
          nullable: true
        deletedAt:
          type: string
          format: date-time
          nullable: true

    PaginationInfo:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer

    PaginatedPatientResponse:
      type: object
      properties:
        previous:
          $ref: '#/components/schemas/PaginationInfo'
          nullable: true
        next:
          $ref: '#/components/schemas/PaginationInfo'
          nullable: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/PatientInfo'
